//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::oauth_accounts::Entity as OauthAccounts;
pub use super::refresh_tokens::Entity as RefreshTokens;
pub use super::tenants::Entity as Tenants;
pub use super::users::Entity as Users;
